#!/bin/bash

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

if ! cargo test
then
    echo "There are some test issues."
    exit 1
fi

if ! cargo test --no-default-features
then
    echo "There are some test issues."
    exit 1
fi

if ! cargo mpirun --np 2 --example mpi_test
then
    echo "There are some mpi test issues."
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

exit 0
