#!/bin/bash


diff=$(cargo fmt -- --check)
result=$?
if [[ ${result} -ne 0 ]] ; then
    echo "There are some code style issues! Run cargo fmt"
fi

if ! cargo test --tests
then
    echo "There are some test issues."
    exit 1
fi

if ! cargo test --no-default-features --features mpi,2d --tests -- --ignored
then
    echo "There are some 2d test issues."
    exit 1
fi

if ! cargo bench --no-run
then
    echo "Benchmarks did not build succesfully"
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo test --doc
then
    echo "There are some doctest issues."
    exit 1
fi

if ! cargo test --no-default-features --features 3d --tests -- --ignored
then
    echo "There are some test issues."
    exit 1
fi


if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi


exit 0
