[package]
name = "derive_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.143", features = ["derive"] }
bevy_ecs = { git = "https://github.com/tehforsch/bevy", branch="no_change_detect", default-features = false, features = []}