box_size:
  min: (-0.1 -0.1 -0.1) kpc
  max: (12.9 12.9 12.9) kpc
timestep:
  max_timestep: 1e-1 Myr
postprocess:
  initial_fraction_ionized_hydrogen: 0.00
  source_strength: 1e49  photons s^-1
sweep:
  directions: 1
  num_timestep_levels: 4
  significant_rate_treshold: 1e20 photons s^-1
  timestep_safety_factor: 0.1
  check_deadlock: false
visualization:
  show_particles: true
  slice:
    - z
    - 2.0 kpc
  color_map:
    type: timestep_level
output:
  fields:
    - ionized_hydrogen_fraction
    - position
    - time
  time_between_snapshots: 10 Myr
  handle_existing_output: delete
input:
  paths:
    - data/ics_64.hdf5
tree:
  tree:
    max_depth: 10
    max_num_particles_per_leaf: 20
simulation:
  final_time: 0.0 Myr
