timestep:
  max_timestep: 3e-6 s
hydrodynamics:
  min_smoothing_length: 1e-7 m
  max_smoothing_length: 1e-1 m
  num_smoothing_neighbours: 20
  initial_gas_energy:
    temperature: 1000 K
    molecular_weight: "4"
domain:
  tree:
    max_depth: 20
    min_depth: 3
    max_num_particles_per_leaf: 1
example:
  num_particles: 100
  max_density: 250.0 kg m^-2
  min_density: 0.05 kg m^-2
  radius: 0.1 m
box_size: (8 8) m
visualization:
  show_particles: True
  color_map:
    type: rank
output:
  fields:
    - velocity
    - mass
    - position
  time_between_snapshots: 0.001 s
  handle_existing_output: delete
